// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_odd_even_sort (
        ap_ready,
        p_read,
        data_1_read,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [12:0] p_read;
input  [12:0] data_1_read;
output  [12:0] ap_return;
input   ap_rst;

wire   [0:0] icmp_ln19_fu_26_p2;

assign ap_ready = 1'b1;

assign ap_return = ((icmp_ln19_fu_26_p2[0:0] == 1'b1) ? data_1_read : p_read);

assign icmp_ln19_fu_26_p2 = ((p_read > data_1_read) ? 1'b1 : 1'b0);

endmodule //top_odd_even_sort
